version: '3.4'

services:
  
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - 5672:5672
      - 8502:15672

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    ports:
      - 8500:8500