version: '3.4'

services:

  consul:
    image: consul:latest
    container_name: eservices-consul
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: eservices-consul
    ports:
      - 8500:8500

  eservices-adminer:
    image: adminer
    container_name: eservices-adminer
    restart: always
    ports:
      - 8501:8080

  rabbit:
    image: rabbitmq:3-management
    container_name: eservices-rabbitmq
    ports:
      - 5672:5672
      - 8502:15672

  eservices-catalog-db:
    image: postgres
    container_name: eservices-catalog-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: eservices-catalog-db
      POSTGRES_PASSWORD: ficticio